version: '3.7'

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: postgres
    env_file:
      - .env
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - smc
  
  question:
    container_name: question
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DATABASE_HOST=host.docker.internal
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      - smc

networks:
  smc: 
    driver: bridge