import { ATTENTION_FOCUS, JUDGMENT_FUNCTION, LIFESTYLE, PERCEPTION_FUNCTION, QUESTION } from "src/constants/common";

type ATTENTION_FOCUS_TYPE = typeof ATTENTION_FOCUS[keyof typeof ATTENTION_FOCUS];
type PERCEPTION_FUNCTION_TYPE = typeof PERCEPTION_FUNCTION[keyof typeof PERCEPTION_FUNCTION];
type JUDGMENT_FUNCTION_TYPE = typeof JUDGMENT_FUNCTION[keyof typeof JUDGMENT_FUNCTION];
type LIFESTYLE_TYPE = typeof LIFESTYLE[keyof typeof LIFESTYLE];

type MBTI_TEMPLATE_TYPE = ATTENTION_FOCUS_TYPE | PERCEPTION_FUNCTION_TYPE | JUDGMENT_FUNCTION_TYPE | LIFESTYLE_TYPE;

type QUESTION_TYPE = keyof typeof QUESTION;
type ANSWER_TYPE<T extends MBTI_TEMPLATE_TYPE> = T;

interface MBTI_TYPE {
  ATTENTION_FOCUS: ATTENTION_FOCUS_TYPE,
  PERCEPTION_FUNCTION: PERCEPTION_FUNCTION_TYPE,
  JUDGMENT_FUNCTION: JUDGMENT_FUNCTION_TYPE,
  LIFESTYLE: LIFESTYLE_TYPE
}

export {
  ATTENTION_FOCUS_TYPE,
  PERCEPTION_FUNCTION_TYPE,
  JUDGMENT_FUNCTION_TYPE,
  LIFESTYLE_TYPE,
  MBTI_TEMPLATE_TYPE,
  QUESTION_TYPE,
  ANSWER_TYPE,
  MBTI_TYPE
}